######################################################################
# Automatically generated by qmake (2.01a) ?t dub 22 16:49:29 2014
######################################################################

TEMPLATE = app
DESTDIR = ../../bin/
INCLUDEPATH += ../memsimlib/
LIBS += -L../../lib/ -lmemsimlib
CONFIG += console debug
QMAKE_CXXFLAGS += -Wfatal-errors

# Input
SOURCES += memsim-cli.cc cmd-parser.cc
HEADERS += memsim-cli.h cmd-parser.h
