######################################################################
# Automatically generated by qmake (2.01a) út dub 22 17:32:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += memsim.ui
