######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 5 01:10:20 2013
######################################################################

TEMPLATE = app
TARGET = memsim
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calendar.h memdevice.h memsim.h memsimul.h memtrace.h
FORMS += memsim.ui
SOURCES += calendar.cc main.cc memdevice.cc memsimul.cc memtrace.cc
